module.exports = {
	Argument: require('./commands/argument'),
	ArgumentCollector: require('./commands/collector'),
	ArgumentType: require('./types/base'),
	Client: require('./client'),
	ClientDatabaseManager: require('./database/ClientDatabaseManager'),
	Command: require('./commands/base'),
	CommandDispatcher: require('./dispatcher'),
	CommandFormatError: require('./errors/command-format'),
	CommandGroup: require('./commands/group'),
	CommandoClient: require('./client'),
	CommandoGuild: require('./extensions/guild'),
	CommandoMessage: require('./extensions/message'),
	CommandoRegistry: require('./registry'),
	DatabaseManager: require('./database/DatabaseManager'),
	FriendlyError: require('./errors/friendly'),
	GuildDatabaseManager: require('./database/GuildDatabaseManager'),
	version: '0.13.0',
}
