import { PermissionsString } from 'discord.js';
import { default as importedEmojiRegex } from 'emoji-regex';
import { GenerateEmbedOptions } from './functions';

export const moderatorPermissions: readonly PermissionsString[] = [
    'BanMembers',
    'DeafenMembers',
    'KickMembers',
    'ManageChannels',
    'ManageEmojisAndStickers',
    'ManageGuild',
    'ManageMessages',
    'ManageNicknames',
    'ManageRoles',
    'ManageThreads',
    'ManageWebhooks',
    'MoveMembers',
    'MuteMembers',
];

export const validateUrlPattern = new RegExp(
    '^(https?:\\/\\/)?' // protocol
    + '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' // domain name
    + '((\\d{1,3}\\.){3}\\d{1,3}))' // OR ip (v4) address
    + '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' // port and path
    + '(\\?[;&a-z\\d%_.~+=-]*)?' // query string
    + '(\\#[-a-z\\d_]*)?$', // fragment locator
    'i'
);

export const defaultGenerateEmbedOptions: Required<Omit<
    GenerateEmbedOptions, 'authorIconURL' | 'authorName' | 'embedTitle' | 'keys' | 'numbered'>
> = {
    ephemeral: false,
    number: 6,
    color: '#4c9f4c',
    useDescription: false,
    title: '',
    inline: false,
    toUser: false,
    dmMsg: '',
    hasObjects: true,
    keyTitle: {},
    keysExclude: [],
    useDocId: false,
    components: [],
    skipMaxButtons: false,
};

export const emojiRegex = new RegExp(`${importedEmojiRegex().source}|\\d{17,20}`, 'g');

export const sevenDays = 604_800;

const rawGoogleLangMap = [
    ['af', 'Afrikaans'],
    ['sq', 'Albanian'],
    ['am', 'Amharic'],
    ['ar', 'Arabic'],
    ['hy', 'Armenian'],
    ['as', 'Assamese'],
    ['ay', 'Aymara'],
    ['az', 'Azerbaijani'],
    ['bm', 'Bambara'],
    ['eu', 'Basque'],
    ['be', 'Belarusian'],
    ['bn', 'Bengali'],
    ['bho', 'Bhojpuri'],
    ['bs', 'Bosnian'],
    ['bg', 'Bulgarian'],
    ['ca', 'Catalan'],
    ['ceb', 'Cebuano'],
    ['zh-CN', 'Chinese (Simplified)'],
    ['zh-TW', 'Chinese (Traditional)'],
    ['co', 'Corsican'],
    ['hr', 'Croatian'],
    ['cs', 'Czech'],
    ['da', 'Danish'],
    ['dv', 'Dhivehi'],
    ['doi', 'Dogri'],
    ['nl', 'Dutch'],
    ['en', 'English'],
    ['eo', 'Esperanto'],
    ['et', 'Estonian'],
    ['ee', 'Ewe'],
    ['fil', 'Filipino (Tagalog)'],
    ['fi', 'Finnish'],
    ['fr', 'French'],
    ['fy', 'Frisian'],
    ['gl', 'Galician'],
    ['ka', 'Georgian'],
    ['de', 'German'],
    ['el', 'Greek'],
    ['gn', 'Guarani'],
    ['gu', 'Gujarati'],
    ['ht', 'Haitian Creole'],
    ['ha', 'Hausa'],
    ['haw', 'Hawaiian'],
    ['he', 'Hebrew'],
    ['hi', 'Hindi'],
    ['hmn', 'Hmong'],
    ['hu', 'Hungarian'],
    ['is', 'Icelandic'],
    ['ig', 'Igbo'],
    ['ilo', 'Ilocano'],
    ['id', 'Indonesian'],
    ['ga', 'Irish'],
    ['it', 'Italian'],
    ['ja', 'Japanese'],
    ['jv', 'Javanese'],
    ['kn', 'Kannada'],
    ['kk', 'Kazakh'],
    ['km', 'Khmer'],
    ['rw', 'Kinyarwanda'],
    ['gom', 'Konkani'],
    ['ko', 'Korean'],
    ['kri', 'Krio'],
    ['ku', 'Kurdish'],
    ['ckb', 'Kurdish (Sorani)'],
    ['ky', 'Kyrgyz'],
    ['lo', 'Lao'],
    ['la', 'Latin'],
    ['lv', 'Latvian'],
    ['ln', 'Lingala'],
    ['lt', 'Lithuanian'],
    ['lg', 'Luganda'],
    ['lb', 'Luxembourgish'],
    ['mk', 'Macedonian'],
    ['mai', 'Maithili'],
    ['mg', 'Malagasy'],
    ['ms', 'Malay'],
    ['ml', 'Malayalam'],
    ['mt', 'Maltese'],
    ['mi', 'Maori'],
    ['mr', 'Marathi'],
    ['mni-Mtei', 'Meiteilon (Manipuri)'],
    ['lus', 'Mizo'],
    ['mn', 'Mongolian'],
    ['my', 'Myanmar (Burmese)'],
    ['ne', 'Nepali'],
    ['no', 'Norwegian'],
    ['ny', 'Nyanja (Chichewa)'],
    ['or', 'Odia (Oriya)'],
    ['om', 'Oromo'],
    ['ps', 'Pashto'],
    ['fa', 'Persian'],
    ['pl', 'Polish'],
    ['pt', 'Portuguese (Portugal, Brazil)'],
    ['pa', 'Punjabi'],
    ['qu', 'Quechua'],
    ['ro', 'Romanian'],
    ['ru', 'Russian'],
    ['sm', 'Samoan'],
    ['sa', 'Sanskrit'],
    ['gd', 'Scots Gaelic'],
    ['nso', 'Sepedi'],
    ['sr', 'Serbian'],
    ['st', 'Sesotho'],
    ['sn', 'Shona'],
    ['sd', 'Sindhi'],
    ['si', 'Sinhala (Sinhalese)'],
    ['sk', 'Slovak'],
    ['sl', 'Slovenian'],
    ['so', 'Somali'],
    ['es', 'Spanish'],
    ['su', 'Sundanese'],
    ['sw', 'Swahili'],
    ['sv', 'Swedish'],
    ['tl', 'Tagalog (Filipino)'],
    ['tg', 'Tajik'],
    ['ta', 'Tamil'],
    ['tt', 'Tatar'],
    ['te', 'Telugu'],
    ['th', 'Thai'],
    ['ti', 'Tigrinya'],
    ['ts', 'Tsonga'],
    ['tr', 'Turkish'],
    ['tk', 'Turkmen'],
    ['ak', 'Twi (Akan)'],
    ['uk', 'Ukrainian'],
    ['ur', 'Urdu'],
    ['ug', 'Uyghur'],
    ['uz', 'Uzbek'],
    ['vi', 'Vietnamese'],
    ['cy', 'Welsh'],
    ['xh', 'Xhosa'],
    ['yi', 'Yiddish'],
    ['yo', 'Yoruba'],
    ['zu', 'Zulu'],
] as const;

export type GoogleLanguageId = (typeof rawGoogleLangMap)[number]['0'];
export type GoogleLanguage = (typeof rawGoogleLangMap)[number]['1'];

export const googleLanguagesMap = new Map(rawGoogleLangMap);
